### ISSUE TITLE
[0.5p] Create main and develop branches

### ISSUE THREAD

**Issue by notlfish** [RokoVarano/hotel_services_backend#1]
## Using ruby 3.0.2 and rails 6.1.4:

rails new hotel_services_backend --api --database postgresql
For main branch:
- [x] Basic README.md file. Acknowlendgement to https://www.behance.net/gallery/26425031/Vespa-Responsive-Redesign
- [x] LICENSE file with all our names. MIT license.

For development branch:
- [x] Add linters from https://github.com/microverseinc/linters-config/tree/master/ror
- [x] Making sure Gemfile is correct
- [x] Configure rack-cors

**Comment by RokoVarano** [comment]
Changes have been implemented.
