### ISSUE TITLE
[Group Task] List Services endpoint/request

### ISSUE THREAD

**Issue by notlfish** [RokoVarano/hotel_services_backend#3]
Define the endpoint and the backend response for the request that enables the List Services page to be rendered.

Give a concrete JSON example to follow.

Add issue for routing/controllers.

**Comment by afcastaneda223** [comment]
Endpoint, GET api/v1/services

services: [{
id: 1,
name: 'pool time',
description: 'bring your own towell'
time: 1.0,
price: USD 10
image_url:  'https://picsum.photos/200/300'
( Use URL and if we have time we create a bucket for AWS )
}]
