### ISSUE TITLE
[0.75p] Service Details endpoint/request [Group Task]

### ISSUE THREAD

**Issue by notlfish** [RokoVarano/hotel_services_backend#5]
Define the endpoint and the backend response for the request that enables the Service Details page to be rendered.

Give a concrete JSON example to follow.

Add issue for routing/controllers.

**Comment by RokoVarano** [comment]
GET

/api/v1/service(services?)/:id

```
response: {
  code: 200,
  service: {
    id: 1,
    name: 'pool time',
    description: 'bring your own towell'
    time: 1.0,
    price: USD 10
    image_url: 'https://picsum.photos/200/300'
  }
}
```

**Comment by RokoVarano** [comment]
Not to be implemented
