### ISSUE TITLE
[0.75p] Add/Delete Service endpoint/request [Group Task]

### ISSUE THREAD

**Issue by notlfish** [RokoVarano/hotel_services_backend#6]
Define the endpoint and the backend response for the request that enables the Add/Delete Service page to be rendered.

Give a concrete JSON example to follow.

Add issue for routing/controllers.

**Comment by RokoVarano** [comment]
## Add

POST /api/v1/services

```
header: {
  "Content-type":  "Application/JSON"
}
```
```
body: {
  name: 'pool time',
  description: 'bring your own towell'
  time: 1.0,
  price: USD 10
  image_url: 'https://picsum.photos/200/300'
  cities: ["Los Angeles", "San Francisco]
}
```
```
response: {
  code: 201,
  text: "Service has been created"
}
```

```
response: {
  code: 500,
  text: "Service creation has failed"
}

## Delete

DELETE /api/v1/service/:id

```
header: {
  "Content-type":  "Application/JSON"
}
```

```
response: {
  code:202,
  message: "Service has been deleted"
}
```
```
response: {
  code:500,
  message: "Service removal has failed"
}
```
