### ISSUE TITLE
[2pt] Finish Services page

### ISSUE THREAD

**Issue by notlfish** [RokoVarano/hotel_services_backend#67]
Make sure that everything is working like it should, in particular, link the images and service names to the given service's details page.

**Comment by RokoVarano** [comment]
- [x] on loading services, there is a call to the API to recover the current services and they are dispatched to the store
- [x] on clicking a service, it redirects to '/services/:id' and in the details page, it displays the service information and pictures.
- [x] if a service is not in the state (for example, by putting directly a non-existing id on the URL) it redirects to '/services'

[Pull request](https://github.com/AdedayoOpeyemi/hotel_services_frontend/pull/20)
